version: '3.8'
services:
  dev:
    build: .
    volumes:
      - .:/app
      - model-data:/models
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
    command: flask run --host=0.0.0.0 --port=${FLASK_PORT} --reload
    environment:
      - FLASK_ENV=development
      - FLASK_APP=main.py
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
  prod:
    build: .
    volumes:
      - model-data:/models
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
    command: gunicorn -w 4 -b 0.0.0.0:${FLASK_PORT} --log-level=debug main:app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
volumes:
  model-data: