version: '3.8'
services:
  dev:
    build: .
    volumes:
      - .:/app
      - model-data:/models
      - temp-data:/app/temp
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
    command: flask run --host=0.0.0.0 --port=${FLASK_PORT} --debug --reload
    environment:
      - FLASK_ENV=development
      - FLASK_APP=main.py
    depends_on:
      - worker
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    command: celery -A celery_worker worker --loglevel=info --pool=solo --uid=nobody --gid=nogroup
    environment:
      - CELERY_WORKER_RUNNING=1
      - CELERYD_FORCE_EXECV=1
    volumes:
      - .:/app
      - model-data:/models
      - temp-data:/app/temp
    depends_on:
      - redis
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
volumes:
  model-data:
  temp-data: