version: '3.8'
services:
  dev:
    build: .
    volumes:
      - .:/app
      - model-data:/models
      - temp-data:/app/temp
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
    command: flask run --host=0.0.0.0 --port=${FLASK_PORT} --debug --reload
    environment:
      - FLASK_ENV=development
      - FLASK_APP=main.py
    depends_on:
      - worker
  #    deploy:
  #      resources:
  #        reservations:
  #          devices:
  #            - driver: nvidia
  #              count: all
  #              capabilities: [ gpu ]
  #  prod:
  #    build: .
  #    volumes:
  #      - model-data:/models
  #    ports:
  #      - "${FLASK_PORT}:${FLASK_PORT}"
  #    command: gunicorn -w 1 -b 0.0.0.0:${FLASK_PORT} --log-level=debug main:app --reload
  #    depends_on:
  #      - worker
  #    deploy:
  #      resources:
  #        reservations:
  #          devices:
  #            - driver: nvidia
  #              count: all
  #              capabilities: [ gpu ]
  worker:
    build: .
    command: celery -A celery_worker.transcription_worker worker --loglevel=debug
    volumes:
      - .:/app
      - model-data:/models
      - temp-data:/app/temp
    depends_on:
      - redis
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
volumes:
  model-data:
  temp-data: