# Use an official nvidia/cuda runtime as a parent image
FROM nvidia/cuda:12.9.1-cudnn-devel-ubuntu20.04

ARG DEBIAN_FRONTEND=noninteractive

# Update and install dependencies
RUN apt-get update && apt-get install -y python3-pip ffmpeg git
RUN pip3 install git+https://github.com/openai/whisper.git

RUN pip3 install gunicorn