services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker      # FROM echobase_transcription-worker:dev
      args:
        BASE_IMAGE: echobase_transcription-worker:dev
    command: >
      watchmedo auto-restart --directory=/app --pattern='*.py' --recursive --
        celery -A EchoBase_transcription.worker.celery_app.celery_app worker --loglevel=debug --pool=solo -E