services:
  api:
    command:
      - uvicorn
      - "EchoBase_transcription.api.app:app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "${API_PORT}"
    environment:
      - API_ENV=production
  worker:
    build:
      args:
        BASE_IMAGE: echobase_transcription-worker:prod
    command: celery -A EchoBase_transcription.worker.celery_app.celery_app worker --loglevel=info --pool=solo