services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    volumes:
      - .:/app
      - model-data:/models
      - temp-data:/app/temp
      - ${CALL_WATCH_PATH}:/app/recordings
    ports:
      - "${API_PORT}:${API_PORT}"
    command: >
      uvicorn EchoBase_transcription.api.app:app
      --host 0.0.0.0 --port ${API_PORT} --reload --log-level debug
    environment:
      - API_ENV=development
      - CALL_WATCH_PATH=/app/recordings
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - worker
    restart: "always"
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
      args:
        BASE_IMAGE: echobase_transcription-worker:prod
    command: >
      celery -A EchoBase_transcription.worker.celery_app.celery_app worker --loglevel=info --pool=solo -E
    environment:
      - CELERY_WORKER_RUNNING=1
      - CELERYD_FORCE_EXECV=1
      - WHISPER_CACHE_DIR=/models
      - HF_HOME=/models/.hf-home
      - HUGGINGFACE_HUB_CACHE=/models/hf-cache
      - CALL_WATCH_PATH=/app/recordings
    volumes:
      - .:/app
      - model-data:/models
      - temp-data:/app/temp
      - ${CALL_WATCH_PATH}:/app/recordings
    depends_on:
      - redis
      - db
    restart: "always"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: "always"
  flower:
    image: mher/flower
    command: celery flower
    working_dir: /data
    ports:
      - 5555:5555
    environment:
      CELERY_BROKER_URL: ${REDIS_URL}
    depends_on:
      - worker
    restart: "always"
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: echobase
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: "always"
volumes:
  model-data:
  temp-data:
  db-data: