services:
  api:
    command:
      - gunicorn
      - "-k"
      - gevent
      - "-w"
      - "2"
      - "--reload"
      - "-b"
      - "0.0.0.0:${FLASK_PORT}"
      - "EchoBase_transcription.api.app:create_app"
    environment:
      - FLASK_ENV=production
  worker:
    build:
      args:
        BASE_IMAGE: echobase_transcription-worker:prod
    command: celery -A EchoBase_transcription.worker.celery_app.celery_app worker --loglevel=info --pool=solo --uid=nobody --gid=nogroup